### ISSUE TITLE
ANR due to stop service

### ISSUE THREAD

**Issue by Ayman-apps** [pawns-app/android-pawns-sdk-demo#2]
Hello, 

Many ANRs are caused due to stopmainroutine. Mostly on Android13 and mostly when app in background.

com.pawns.ndk.PawnsCore.StopMainRoutine
ANR triggered by slow operations in main thread

        main (native):tid=1 systid=17203 
#00 pc 0xb0e0 [anon:scudo:primary]
       at com.pawns.ndk.PawnsCore.StopMainRoutine(Native method)
       at com.pawns.sdk.internal.service.PeerServiceForeground.stopSharing(PeerServiceForeground.kt:282)
       at com.pawns.sdk.internal.service.PeerServiceForeground.stopService(PeerServiceForeground.kt:260)
       at com.pawns.sdk.internal.service.PeerServiceForeground.onCreate(PeerServiceForeground.kt:125)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4616)
       at android.app.ActivityThread.-$$Nest$mhandleCreateService(unavailable)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2247)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:8061)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:923)

**Comment by LaurynasM-iproyal** [comment]
Moved PawnsCore.StopMainRoutine to a separate coroutine scope with Dispatchers.IO. This should help reducing number of ANRs received. Available later this week in 1.3.2

**Comment by Ayman-apps** [comment]
Issue still there in 1.3.2
 main (native):tid=1 systid=31324 
#00 pc 0x9b50 [anon:scudo:primary]
       at com.pawns.ndk.PawnsCore.StopMainRoutine(Native method)
       at com.pawns.sdk.internal.service.PeerServiceForeground.onDestroy(PeerServiceForeground.kt:146)
       at android.app.ActivityThread.handleStopService(ActivityThread.java:4816)
       at android.app.ActivityThread.-$$Nest$mhandleStopService(unavailable)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2271)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:8061)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:923)

**Comment by LaurynasM-iproyal** [comment]
Thank you for a new stacktrace, I see that there is now another place that might be causing an issue - **onDestroy** method. I will have a look at that

**Comment by LaurynasM-iproyal** [comment]
Issue will be fixed in 1.3.3
