### ISSUE TITLE
Getting error bad notification even when calling Background service

### ISSUE THREAD

**Issue by Ayman-apps** [pawns-app/android-pawns-sdk-demo#7]
**Using Pawns like this:**
 new Pawns.Builder(this)
                                   .apiKey("API")
                                   .serviceType(ServiceType.BACKGROUND)
                                //   .loggerEnabled(true) //for testing
                                   .build();
                           Pawns.Companion.getInstance().startSharing(this);

**We are not calling this:**
 .serviceConfig(
                                                    new ServiceConfig(
                                                            R.string.app_name,
                                                            R.string.updating_results,
                                                            R.drawable.footballicon2,
                                                            ServiceNotificationPriority.LOW,
                                                            null
                                                    )

**Having both services in the manifest (background and foreground) but only using background**

**Error:**
  Fatal Exception: android.app.RemoteServiceException$CannotPostForegroundServiceNotificationException: Bad notification for startForeground
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2189)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2487)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:243)
       at android.os.Looper.loop(Looper.java:338)
       at android.app.ActivityThread.main(ActivityThread.java:8470)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1064)

**Why is notification even called??**

**Comment by laurynas-pawns** [comment]
Hello. It looks like our method `startSharing` is launching correct service type. Background service itself is not using any notifications and it is launched by using android service method `startService(intent)`, which does not have a parameter to take notification. Is there any chance that this error is seen by users who use older version of your application and that version used **FOREGROUND** service type?

**Comment by Ayman-apps** [comment]
I don't think so. All our logs show that it is latest version and it is calling background service, but error is happening for some reason which we cannot reproduce but happening to users on production.

**Comment by laurynas-pawns** [comment]
It could be a result of users that used previous application version that already have foreground service launched. For example

Version 1.0.0 launched foreground
Version 1.0.1 launches background, but application still have foreground running after update. After receiving error the foreground service will stop and then it will only launch background. 

Currently there is no check in SDK for swapping service type in different versions to make sure that foreground is stopped before launching background. We will enhance starting method with additional check for this case.
